# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DNPyUI.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DNPy(object):
    def setupUi(self, DNPy):
        DNPy.setObjectName("DNPy")
        DNPy.resize(600, 856)
        self.gridLayout = QtWidgets.QGridLayout(DNPy)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(DNPy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_3)
        self.formLayout.setObjectName("formLayout")
        self.pathLabel = QtWidgets.QLabel(self.groupBox_3)
        self.pathLabel.setObjectName("pathLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.pathLabel)
        self.path = QtWidgets.QLineEdit(self.groupBox_3)
        self.path.setObjectName("path")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.path)
        self.powerFileLabel = QtWidgets.QLabel(self.groupBox_3)
        self.powerFileLabel.setObjectName("powerFileLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.powerFileLabel)
        self.powerFile = QtWidgets.QLineEdit(self.groupBox_3)
        self.powerFile.setObjectName("powerFile")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.powerFile)
        self.t1CalcLabel_3 = QtWidgets.QLabel(self.groupBox_3)
        self.t1CalcLabel_3.setObjectName("t1CalcLabel_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.t1CalcLabel_3)
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comboBox_3)
        self.ftWindowLabel = QtWidgets.QLabel(self.groupBox_3)
        self.ftWindowLabel.setObjectName("ftWindowLabel")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.ftWindowLabel)
        self.ftWindow = QtWidgets.QSpinBox(self.groupBox_3)
        self.ftWindow.setMaximum(10000)
        self.ftWindow.setSingleStep(10)
        self.ftWindow.setProperty("value", 200)
        self.ftWindow.setObjectName("ftWindow")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.ftWindow)
        self.maxWinLabel = QtWidgets.QLabel(self.groupBox_3)
        self.maxWinLabel.setObjectName("maxWinLabel")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.maxWinLabel)
        self.lB = QtWidgets.QSpinBox(self.groupBox_3)
        self.lB.setMaximum(100)
        self.lB.setSingleStep(100)
        self.lB.setProperty("value", 2)
        self.lB.setObjectName("lB")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.lB)
        self.lBLabel = QtWidgets.QLabel(self.groupBox_3)
        self.lBLabel.setObjectName("lBLabel")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.lBLabel)
        self.maxWin = QtWidgets.QSpinBox(self.groupBox_3)
        self.maxWin.setMaximum(100000)
        self.maxWin.setSingleStep(100)
        self.maxWin.setProperty("value", 1000)
        self.maxWin.setObjectName("maxWin")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.maxWin)
        self.evalPathLabel = QtWidgets.QLabel(self.groupBox_3)
        self.evalPathLabel.setObjectName("evalPathLabel")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.evalPathLabel)
        self.evalPath = QtWidgets.QLineEdit(self.groupBox_3)
        self.evalPath.setObjectName("evalPath")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.evalPath)
        self.mistLabel = QtWidgets.QLabel(self.groupBox_3)
        self.mistLabel.setObjectName("mistLabel")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.mistLabel)
        self.miscWidget = QtWidgets.QWidget(self.groupBox_3)
        self.miscWidget.setMinimumSize(QtCore.QSize(0, 100))
        self.miscWidget.setObjectName("miscWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.miscWidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.offCor = QtWidgets.QCheckBox(self.miscWidget)
        self.offCor.setChecked(True)
        self.offCor.setObjectName("offCor")
        self.gridLayout_3.addWidget(self.offCor, 0, 1, 1, 1)
        self.dumpToCsv = QtWidgets.QCheckBox(self.miscWidget)
        self.dumpToCsv.setObjectName("dumpToCsv")
        self.gridLayout_3.addWidget(self.dumpToCsv, 1, 0, 1, 2)
        self.kSigmaCalc = QtWidgets.QCheckBox(self.miscWidget)
        self.kSigmaCalc.setObjectName("kSigmaCalc")
        self.gridLayout_3.addWidget(self.kSigmaCalc, 2, 0, 1, 1)
        self.basCor = QtWidgets.QCheckBox(self.miscWidget)
        self.basCor.setChecked(True)
        self.basCor.setTristate(False)
        self.basCor.setObjectName("basCor")
        self.gridLayout_3.addWidget(self.basCor, 0, 0, 1, 1)
        self.Debug = QtWidgets.QCheckBox(self.miscWidget)
        self.Debug.setObjectName("Debug")
        self.gridLayout_3.addWidget(self.Debug, 3, 0, 1, 1)
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.miscWidget)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_2 = QtWidgets.QGroupBox(DNPy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout_2.setObjectName("formLayout_2")
        self.lSLabel = QtWidgets.QLabel(self.groupBox_2)
        self.lSLabel.setObjectName("lSLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lSLabel)
        self.lS = QtWidgets.QSpinBox(self.groupBox_2)
        self.lS.setMaximum(1000)
        self.lS.setProperty("value", 70)
        self.lS.setObjectName("lS")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lS)
        self.rSLabel = QtWidgets.QLabel(self.groupBox_2)
        self.rSLabel.setObjectName("rSLabel")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.rSLabel)
        self.rS = QtWidgets.QSpinBox(self.groupBox_2)
        self.rS.setMaximum(1000)
        self.rS.setProperty("value", 110)
        self.rS.setObjectName("rS")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.rS)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.t1SeriesEval = QtWidgets.QGroupBox(DNPy)
        self.t1SeriesEval.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t1SeriesEval.sizePolicy().hasHeightForWidth())
        self.t1SeriesEval.setSizePolicy(sizePolicy)
        self.t1SeriesEval.setSizeIncrement(QtCore.QSize(1, 2))
        self.t1SeriesEval.setBaseSize(QtCore.QSize(1, 1))
        self.t1SeriesEval.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.t1SeriesEval.setFlat(False)
        self.t1SeriesEval.setCheckable(True)
        self.t1SeriesEval.setObjectName("t1SeriesEval")
        self.formLayout_3 = QtWidgets.QFormLayout(self.t1SeriesEval)
        self.formLayout_3.setObjectName("formLayout_3")
        self.t1CalcLabel = QtWidgets.QLabel(self.t1SeriesEval)
        self.t1CalcLabel.setObjectName("t1CalcLabel")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.t1CalcLabel)
        self.lSt1Label = QtWidgets.QLabel(self.t1SeriesEval)
        self.lSt1Label.setObjectName("lSt1Label")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lSt1Label)
        self.rSt1Label = QtWidgets.QLabel(self.t1SeriesEval)
        self.rSt1Label.setObjectName("rSt1Label")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.rSt1Label)
        self.comboBox = QtWidgets.QComboBox(self.t1SeriesEval)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        self.lSt1 = QtWidgets.QSpinBox(self.t1SeriesEval)
        self.lSt1.setMaximum(1000)
        self.lSt1.setProperty("value", 70)
        self.lSt1.setObjectName("lSt1")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lSt1)
        self.rSt1 = QtWidgets.QSpinBox(self.t1SeriesEval)
        self.rSt1.setMaximum(1000)
        self.rSt1.setProperty("value", 75)
        self.rSt1.setObjectName("rSt1")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.rSt1)
        self.t1SeriesPolDeg = QtWidgets.QSpinBox(self.t1SeriesEval)
        self.t1SeriesPolDeg.setMaximum(10)
        self.t1SeriesPolDeg.setProperty("value", 1)
        self.t1SeriesPolDeg.setObjectName("t1SeriesPolDeg")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.t1SeriesPolDeg)
        self.t1SeriesPolDegLabel = QtWidgets.QLabel(self.t1SeriesEval)
        self.t1SeriesPolDegLabel.setObjectName("t1SeriesPolDegLabel")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.t1SeriesPolDegLabel)
        self.verticalLayout.addWidget(self.t1SeriesEval)
        self.makeFigs = QtWidgets.QGroupBox(DNPy)
        self.makeFigs.setCheckable(True)
        self.makeFigs.setObjectName("makeFigs")
        self.formLayout_4 = QtWidgets.QFormLayout(self.makeFigs)
        self.formLayout_4.setObjectName("formLayout_4")
        self.plotExtsLabel = QtWidgets.QLabel(self.makeFigs)
        self.plotExtsLabel.setObjectName("plotExtsLabel")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.plotExtsLabel)
        self.widget = QtWidgets.QWidget(self.makeFigs)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.jpg = QtWidgets.QCheckBox(self.widget)
        self.jpg.setChecked(True)
        self.jpg.setObjectName("jpg")
        self.horizontalLayout.addWidget(self.jpg)
        self.png = QtWidgets.QCheckBox(self.widget)
        self.png.setObjectName("png")
        self.horizontalLayout.addWidget(self.png)
        self.pdf = QtWidgets.QCheckBox(self.widget)
        self.pdf.setObjectName("pdf")
        self.horizontalLayout.addWidget(self.pdf)
        self.eps = QtWidgets.QCheckBox(self.widget)
        self.eps.setObjectName("eps")
        self.horizontalLayout.addWidget(self.eps)
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.widget)
        self.figSizeLabel = QtWidgets.QLabel(self.makeFigs)
        self.figSizeLabel.setObjectName("figSizeLabel")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.figSizeLabel)
        self.widget_2 = QtWidgets.QWidget(self.makeFigs)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 27))
        self.widget_2.setObjectName("widget_2")
        self.figWidth = QtWidgets.QSpinBox(self.widget_2)
        self.figWidth.setGeometry(QtCore.QRect(50, 0, 51, 24))
        self.figWidth.setProperty("value", 13)
        self.figWidth.setObjectName("figWidth")
        self.figHeight = QtWidgets.QSpinBox(self.widget_2)
        self.figHeight.setGeometry(QtCore.QRect(130, 0, 51, 24))
        self.figHeight.setProperty("value", 8)
        self.figHeight.setObjectName("figHeight")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setGeometry(QtCore.QRect(110, 0, 16, 21))
        self.label_2.setObjectName("label_2")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.widget_2)
        self.label = QtWidgets.QLabel(self.makeFigs)
        self.label.setObjectName("label")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label)
        self.spinBox = QtWidgets.QSpinBox(self.makeFigs)
        self.spinBox.setMaximum(1000)
        self.spinBox.setSingleStep(10)
        self.spinBox.setProperty("value", 250)
        self.spinBox.setObjectName("spinBox")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spinBox)
        self.verticalLayout.addWidget(self.makeFigs)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(DNPy)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)
        self.CopyrightBox = QtWidgets.QWidget(DNPy)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CopyrightBox.sizePolicy().hasHeightForWidth())
        self.CopyrightBox.setSizePolicy(sizePolicy)
        self.CopyrightBox.setObjectName("CopyrightBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.CopyrightBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.CopyrightBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.CopyrightBox)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.label_3 = QtWidgets.QLabel(self.CopyrightBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.gridLayout.addWidget(self.CopyrightBox, 2, 0, 1, 1)

        self.retranslateUi(DNPy)
        self.buttonBox.accepted.connect(DNPy.accept)
        self.buttonBox.rejected.connect(DNPy.reject)
        QtCore.QMetaObject.connectSlotsByName(DNPy)

    def retranslateUi(self, DNPy):
        _translate = QtCore.QCoreApplication.translate
        DNPy.setWindowTitle(_translate("DNPy", "DNPy - ODNP evaluation"))
        self.groupBox_3.setTitle(_translate("DNPy", "General"))
        self.pathLabel.setText(_translate("DNPy", "Experiment folder"))
        self.powerFileLabel.setText(_translate("DNPy", "Powers file"))
        self.t1CalcLabel_3.setText(_translate("DNPy", "Auto phasing routine"))
        self.comboBox_3.setItemText(0, _translate("DNPy", "First experiment"))
        self.comboBox_3.setItemText(1, _translate("DNPy", "All experiments"))
        self.comboBox_3.setItemText(2, _translate("DNPy", "No auto phasing"))
        self.ftWindowLabel.setText(_translate("DNPy", "Fourier transformation window [Hz]"))
        self.maxWinLabel.setText(_translate("DNPy", "Maximum frequency tolerance [Hz]"))
        self.lBLabel.setText(_translate("DNPy", "Line broadening [Hz]"))
        self.evalPathLabel.setText(_translate("DNPy", "Evaluation folder name"))
        self.evalPath.setText(_translate("DNPy", "eval"))
        self.mistLabel.setText(_translate("DNPy", "Misc"))
        self.offCor.setText(_translate("DNPy", "Offset correction"))
        self.dumpToCsv.setText(_translate("DNPy", "Export results to csv"))
        self.kSigmaCalc.setText(_translate("DNPy", "Calculate kSignma"))
        self.basCor.setText(_translate("DNPy", "Baseline correction"))
        self.Debug.setText(_translate("DNPy", "Debug"))
        self.groupBox_2.setTitle(_translate("DNPy", "DNP"))
        self.lSLabel.setText(_translate("DNPy", "DNP left shift number"))
        self.rSLabel.setText(_translate("DNPy", "DNP right shift number"))
        self.t1SeriesEval.setTitle(_translate("DNPy", "T1"))
        self.t1CalcLabel.setText(_translate("DNPy", "T1 calculation data"))
        self.lSt1Label.setText(_translate("DNPy", "T1 left shift number"))
        self.rSt1Label.setText(_translate("DNPy", "T1 right shift number"))
        self.comboBox.setItemText(0, _translate("DNPy", "Phase cycled real"))
        self.comboBox.setItemText(1, _translate("DNPy", "Phase cycled magnitude"))
        self.comboBox.setItemText(2, _translate("DNPy", "Real"))
        self.comboBox.setItemText(3, _translate("DNPy", "Magnitude"))
        self.t1SeriesPolDegLabel.setText(_translate("DNPy", "T1 series polynomial degree"))
        self.makeFigs.setTitle(_translate("DNPy", "Figures"))
        self.plotExtsLabel.setText(_translate("DNPy", "Fromats"))
        self.jpg.setText(_translate("DNPy", "JPEG"))
        self.png.setText(_translate("DNPy", "PNG"))
        self.pdf.setText(_translate("DNPy", "PDF"))
        self.eps.setText(_translate("DNPy", "EPS"))
        self.figSizeLabel.setText(_translate("DNPy", "Figure size (width, height) [cm]"))
        self.label_2.setText(_translate("DNPy", "x"))
        self.label.setText(_translate("DNPy", "DPI [ppi]"))
        self.label_4.setText(_translate("DNPy", "<html><head/><body><p><img src=\"./logo_red_shade_nostroke_120_small.png\"/></p></body></html>"))
        self.label_5.setText(_translate("DNPy", "<html><head/><body><p><a href=\"http://www.spintoolbox.com/\"><span style=\" text-decoration: underline; color:#0000ff;\">SpinToolbox.com</span></a></p></body></html>"))
        self.label_3.setText(_translate("DNPy", "Code and design by M. Hadi Timachi"))

#import Resources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DNPy = QtWidgets.QDialog()
    ui = Ui_DNPy()
    ui.setupUi(DNPy)
    DNPy.show()
    sys.exit(app.exec_())

